const actionTypes = {
  INITIALIZE_HOME_PAGE: '__INITIALIZE_HOME_PAGE',
  INITIALIZE_DASHBOARD_PAGE: '__INITIALIZE_DASHBOARD_PAGE',

  UPDATE_TASK: '__UPDATE_TASK',
  DELETE_TASK: '__DELETE_TASK',
};

export default actionTypes;
